package com.vignesh.leetcodechecker.pipeline

/**
 * Core data models for the Deep Analysis pipeline — ported from Python usecase_4.
 *
 * These include: Document, Chunk, SearchResult, SearchPlan, StepResult,
 * CostGuard, GraphMemory, and all JSON schema definitions.
 */

// ════════════════════════════════════════════════════════════════════════
// Document / Chunk / SearchResult — core retrieval types
// ════════════════════════════════════════════════════════════════════════

data class PipelineDocument(
    val content: String,
    val docId: String,
    val metadata: MutableMap<String, String> = mutableMapOf()
)

data class PipelineChunk(
    val text: String,
    val chunkId: String,
    val docId: String,
    val startChar: Int = 0,
    val endChar: Int = 0,
    val metadata: MutableMap<String, String> = mutableMapOf(),
    var embedding: List<Double>? = null
)

data class PipelineSearchResult(
    val chunk: PipelineChunk,
    val score: Double,
    val rank: Int = 0
)

// ════════════════════════════════════════════════════════════════════════
// SearchPlan — generated by query planner from user's question
// ════════════════════════════════════════════════════════════════════════

data class PipelineSearchPlan(
    val domain: String = "general",
    val focusTopic: String = "",
    val perspective: String = "an industry analyst",
    val primaryQuestion: String = "",
    val companies: List<PipelineCompanyInfo> = emptyList(),
    val groundingQueries: List<String> = emptyList(),
    val newsQueries: List<String> = emptyList(),
    val secFulltextQueries: List<String> = emptyList(),
    val memorySeedEdges: List<Triple<String, String, String>> = emptyList(),
    val financialRetrievalQuery: String = "",
    val qualitativeRetrievalQuery: String = "",
    val companyPatterns: List<Pair<String, String>> = emptyList(),
    val tickerToCik: Map<String, String> = emptyMap(),
    val extractionCompanies: Map<String, String> = emptyMap()
)

data class PipelineCompanyInfo(
    val name: String,
    val ticker: String,
    val cik: String = "",
    val role: String = "primary"
)

// ════════════════════════════════════════════════════════════════════════
// Step tracking
// ════════════════════════════════════════════════════════════════════════

data class StepResult(
    val name: String,
    val details: String = ""
)

// ════════════════════════════════════════════════════════════════════════
// Graph Memory — persistent knowledge graph across turns
// ════════════════════════════════════════════════════════════════════════

class GraphMemory {
    private val edges = mutableListOf<Triple<String, String, String>>()

    fun addEdge(source: String, relation: String, target: String) {
        val triple = Triple(source, relation, target)
        if (triple !in edges) edges.add(triple)
    }

    fun allEdges(): List<Triple<String, String, String>> = edges.toList()

    fun format(): String {
        if (edges.isEmpty()) return "(empty)"
        return edges.joinToString("\n") { (s, r, t) -> "  ($s) --[$r]--> ($t)" }
    }
}

// ════════════════════════════════════════════════════════════════════════
// Cost Guard — budget tracking (ported from Python)
// ════════════════════════════════════════════════════════════════════════

class PipelineCostGuard(
    val budgetUsd: Double = 0.50
) {
    var totalInputTokens: Int = 0; private set
    var totalOutputTokens: Int = 0; private set
    var totalEmbeddingTokens: Int = 0; private set
    var totalCostUsd: Double = 0.0; private set
    var apiCalls: Int = 0; private set
    var cacheHits: Int = 0; private set

    private fun priceFor(model: String): Pair<Double, Double> {
        val m = model.lowercase()
        return when {
            "2.5-flash" in m -> 0.15 to 0.60
            "2.0-flash" in m -> 0.10 to 0.40
            "1.5-flash" in m -> 0.075 to 0.30
            "2.5-pro" in m -> 1.25 to 10.00
            "embedding" in m -> 0.0 to 0.0
            else -> 0.15 to 0.60  // conservative fallback
        }
    }

    fun record(inputTokens: Int, outputTokens: Int, model: String): Double {
        val (ip, op) = priceFor(model)
        val cost = (inputTokens * ip + outputTokens * op) / 1_000_000.0
        totalInputTokens += inputTokens
        totalOutputTokens += outputTokens
        totalCostUsd += cost
        apiCalls++
        return cost
    }

    fun recordEmbedding(tokens: Int) {
        totalEmbeddingTokens += tokens
    }

    fun check() {
        if (totalCostUsd >= budgetUsd) {
            throw BudgetExceededException(
                "Budget cap reached! Spent ~\$${String.format("%.4f", totalCostUsd)} " +
                "(limit \$${String.format("%.2f", budgetUsd)}). " +
                "Tokens: $totalInputTokens in / $totalOutputTokens out / $apiCalls API calls"
            )
        }
    }
}

class BudgetExceededException(message: String) : RuntimeException(message)

// ════════════════════════════════════════════════════════════════════════
// JSON Schemas for Gemini structured output
// ════════════════════════════════════════════════════════════════════════

object PipelineSchemas {
    val PLAN: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "steps" to mapOf("type" to "array", "items" to mapOf("type" to "string"))
        )
    )

    val CRITIQUE: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "overall_score" to mapOf("type" to "number"),
            "depth" to mapOf("type" to "integer"),
            "evidence" to mapOf("type" to "integer"),
            "causality" to mapOf("type" to "integer"),
            "actionability" to mapOf("type" to "integer"),
            "verdict" to mapOf("type" to "string", "enum" to listOf("PASS", "NEEDS_REFINEMENT")),
            "feedback" to mapOf("type" to "string")
        )
    )

    val STRATEGY: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "strategies" to mapOf(
                "type" to "array",
                "items" to mapOf(
                    "type" to "object",
                    "properties" to mapOf(
                        "name" to mapOf("type" to "string"),
                        "actions" to mapOf("type" to "array", "items" to mapOf("type" to "string")),
                        "cost" to mapOf("type" to "string"),
                        "expected_outcome" to mapOf("type" to "string")
                    )
                )
            )
        )
    )

    val MEMORY: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "edges" to mapOf(
                "type" to "array",
                "items" to mapOf(
                    "type" to "object",
                    "properties" to mapOf(
                        "source" to mapOf("type" to "string"),
                        "relation" to mapOf("type" to "string"),
                        "target" to mapOf("type" to "string")
                    )
                )
            )
        )
    )

    val REFINEMENT: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "queries" to mapOf("type" to "array", "items" to mapOf("type" to "string"))
        )
    )

    fun companySchema(): Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "name" to mapOf("type" to "string"),
            "current_revenue_b" to mapOf("type" to "number"),
            "previous_revenue_b" to mapOf("type" to "number"),
            "yoy_growth_pct" to mapOf("type" to "number"),
            "operating_margin_pct" to mapOf("type" to "number")
        )
    )

    fun buildExtractionSchema(plan: PipelineSearchPlan): Map<String, Any> {
        val companiesProps = mutableMapOf<String, Any>()
        for ((ticker, _) in plan.extractionCompanies) {
            companiesProps[ticker] = companySchema()
        }
        if (companiesProps.isEmpty()) {
            companiesProps["COMPANY"] = companySchema()
        }
        return mapOf(
            "type" to "object",
            "properties" to mapOf(
                "companies" to mapOf(
                    "type" to "object",
                    "properties" to companiesProps
                ),
                "quarter" to mapOf("type" to "string")
            )
        )
    }
}

// ════════════════════════════════════════════════════════════════════════
// Planner Schema for query_planner
// ════════════════════════════════════════════════════════════════════════

object PlannerSchemas {
    val SEARCH_PLAN: Map<String, Any> = mapOf(
        "type" to "object",
        "properties" to mapOf(
            "domain" to mapOf("type" to "string"),
            "focus_topic" to mapOf("type" to "string"),
            "perspective" to mapOf("type" to "string"),
            "primary_question" to mapOf("type" to "string"),
            "companies" to mapOf(
                "type" to "array",
                "items" to mapOf(
                    "type" to "object",
                    "properties" to mapOf(
                        "name" to mapOf("type" to "string"),
                        "ticker" to mapOf("type" to "string"),
                        "role" to mapOf("type" to "string")
                    )
                )
            ),
            "grounding_queries" to mapOf(
                "type" to "array",
                "items" to mapOf("type" to "string")
            ),
            "news_queries" to mapOf(
                "type" to "array",
                "items" to mapOf("type" to "string")
            ),
            "sec_fulltext_queries" to mapOf(
                "type" to "array",
                "items" to mapOf("type" to "string")
            ),
            "financial_retrieval_query" to mapOf("type" to "string"),
            "qualitative_retrieval_query" to mapOf("type" to "string"),
            "memory_seeds" to mapOf(
                "type" to "array",
                "items" to mapOf(
                    "type" to "object",
                    "properties" to mapOf(
                        "source" to mapOf("type" to "string"),
                        "relation" to mapOf("type" to "string"),
                        "target" to mapOf("type" to "string")
                    )
                )
            )
        )
    )
}
