from typing import List
import math

class Solution:
    def maximumScore(self, grid: List[List[int]]) -> int:
        n = len(grid)
        
        # The score is generated by horizontal adjacencies, so at least 2 columns are needed.
        if n == 1:
            return 0

        # Precompute column-wise prefix sums for efficient range sum queries.
        # col_prefix_sum[j][i] = sum of grid[k][j] for k from 0 to i-1.
        col_prefix_sum = [[0] * (n + 1) for _ in range(n)]
        for j in range(n):
            for i in range(n):
                col_prefix_sum[j][i + 1] = col_prefix_sum[j][i] + grid[i][j]

        # dp_prev[k_idx] stores the max score considering columns 0..j-1,
        # with the high-water mark for column j-1 being k = k_idx - 1.
        # The high-water mark k can be from -1 to n-1. We map this to k_idx from 0 to n.
        dp_prev = [0] * (n + 1)

        # Iterate through columns from j=1 to n-1, building up the solution.
        for j in range(1, n):
            dp_curr = [0] * (n + 1)
            
            # To optimize the transition from O(n) to O(1), we precompute prefix and suffix maximums.
            # These are based on the state of the previous column, dp_prev (for column j-1).
            
            # prefix_max[k_idx] = max_{i_idx <= k_idx} (dp_prev[i_idx] - col_prefix_sum[j-1][i_idx])
            prefix_max = [-math.inf] * (n + 1)
            prefix_max[0] = dp_prev[0] - col_prefix_sum[j - 1][0]
            for k_idx in range(1, n + 1):
                prefix_max[k_idx] = max(prefix_max[k_idx - 1], dp_prev[k_idx] - col_prefix_sum[j - 1][k_idx])

            # suffix_max[k_idx] = max_{i_idx >= k_idx} (dp_prev[i_idx] + col_prefix_sum[j][i_idx])
            suffix_max = [-math.inf] * (n + 1)
            suffix_max[n] = dp_prev[n] + col_prefix_sum[j][n]
            for k_idx in range(n - 1, -1, -1):
                suffix_max[k_idx] = max(suffix_max[k_idx + 1], dp_prev[k_idx] + col_prefix_sum[j][k_idx])

            # Compute dp_curr for column j using the precomputed values.
            for k_j_idx in range(n + 1):
                # Case 1: k_j > k_{j-1}. Score is added from column j-1.
                val1 = -math.inf
                if k_j_idx > 0:
                    val1 = col_prefix_sum[j - 1][k_j_idx] + prefix_max[k_j_idx - 1]
                
                # Case 2: k_j = k_{j-1}. No score added at this boundary.
                val2 = dp_prev[k_j_idx]
                
                # Case 3: k_j < k_{j-1}. Score is added from column j.
                val3 = -math.inf
                if k_j_idx < n:
                    val3 = -col_prefix_sum[j][k_j_idx] + suffix_max[k_j_idx + 1]
                
                dp_curr[k_j_idx] = max(val1, val2, val3)
            
            dp_prev = dp_curr

        return max(dp_prev)