"""
Query Planner — LLM-powered dynamic search plan generator.

This module replaces the hardcoded search queries, SEC tickers, and news
queries that were previously baked into web_fetcher.py and agents.py.

Given ANY user question, it asks the LLM to decompose the question into a
structured ``SearchPlan`` that drives every downstream data-fetching and
analysis step.

Flow
----
    User prompt
        ↓
    generate_search_plan(prompt, llm)
        ↓
    SearchPlan dataclass
        ↓ consumed by
    web_fetcher.py  — grounding_queries, ciks, news_queries, sec_queries
    agents.py       — analysis_context (prompts, schemas, perspective)
    metadata_enricher.py — company_patterns
    orchestrator.py — memory seeds, retrieval queries

Ref: https://ai.google.dev/gemini-api/docs/text-generation
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from llm_client import GeminiClient

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════
# SearchPlan dataclass — the single source of truth for a user query
# ═══════════════════════════════════════════════════════════════════════════
@dataclass
class SearchPlan:
    """Structured research plan generated by the LLM from a user prompt.

    Every downstream module reads from this plan instead of using hardcoded
    values. This makes the pipeline truly question-adaptive.
    """
    # ── Domain & framing ─────────────────────────────────────────
    domain: str = "general"                        # e.g., "semiconductor", "cloud computing"
    focus_topic: str = ""                          # e.g., "quantum computing R&D"
    perspective: str = "an industry analyst"        # who the report is written for
    primary_question: str = ""                     # rewritten core question
    original_prompt: str = ""                      # verbatim user prompt

    # ── Companies to research ────────────────────────────────────
    # Each dict: {"name": "Nvidia Corporation", "ticker": "NVDA",
    #             "cik": "0001045810", "role": "primary"}
    companies: list[dict[str, str]] = field(default_factory=list)

    # ── Data-fetching queries ────────────────────────────────────
    # Grounded search: [{"query": "...", "company": "NVDA"}]
    grounding_queries: list[dict[str, str]] = field(default_factory=list)
    # Google News RSS: ["Nvidia+quantum+computing"]
    news_queries: list[str] = field(default_factory=list)
    # SEC EDGAR full-text: ["Nvidia quantum computing R&D"]
    sec_fulltext_queries: list[str] = field(default_factory=list)

    # ── Retrieval queries (for hybrid search after indexing) ─────
    financial_retrieval_query: str = ""
    qualitative_retrieval_query: str = ""

    # ── Memory seeds ─────────────────────────────────────────────
    # [{"source": "Nvidia", "relation": "LeadsIn", "target": "GPU AI Computing"}]
    memory_seeds: list[dict[str, str]] = field(default_factory=list)

    # ── Extraction schema (for financial data extraction) ────────
    # Dynamic: keys are tickers, values are company names
    extraction_companies: dict[str, str] = field(default_factory=dict)

    @property
    def ticker_to_cik(self) -> dict[str, str]:
        """Map ticker → CIK from the companies list."""
        return {
            c["ticker"]: c.get("cik", "")
            for c in self.companies
            if c.get("ticker") and c.get("cik")
        }

    @property
    def company_patterns(self) -> list[tuple[str, str]]:
        """Generate (regex_pattern, ticker) pairs for metadata enrichment."""
        patterns = []
        for c in self.companies:
            parts = [re.escape(c.get("ticker", "").lower())]
            name = c.get("name", "")
            if name:
                # Add the full name and individual significant words
                parts.append(re.escape(name.lower()))
                for word in name.split():
                    if len(word) > 3 and word.lower() not in {"inc.", "corp.", "corp", "inc", "ltd", "the", "and", "llc"}:
                        parts.append(re.escape(word.lower()))
            # Add any aliases the LLM may have included
            for alias in c.get("aliases", "").split(","):
                alias = alias.strip()
                if alias:
                    parts.append(re.escape(alias.lower()))
            pattern = "|".join(p for p in parts if p)
            if pattern:
                patterns.append((pattern, c.get("ticker", "UNKNOWN")))
        return patterns


# ═══════════════════════════════════════════════════════════════════════════
# LLM prompt + schema for plan generation
# ═══════════════════════════════════════════════════════════════════════════
_PLANNER_SYSTEM = """\
You are a strategic research planner. Given a user's analysis question,
generate a structured research plan as JSON.

Your plan must identify:
1. The industry domain and focus topic
2. Key companies/entities to research (with stock tickers and SEC CIK numbers)
3. Specific web search queries to gather real-time data
4. News search terms and SEC filing search terms
5. The analytical perspective and framing

IMPORTANT RULES:
- CIK numbers must be zero-padded to 10 digits (e.g., "0001045810" for Nvidia)
- If you don't know a CIK number, use an empty string ""
- Generate 4-8 grounding queries covering: earnings/financials, R&D, competitive analysis, and the specific focus topic
- News queries use "+" instead of spaces (URL-encoded for Google News RSS)
- Generate 2-4 memory seed edges capturing well-known strategic relationships
- The perspective should describe who the analysis is written for
- extraction_companies maps ticker → display name for financial data extraction
"""

_PLANNER_SCHEMA = {
    "type": "object",
    "properties": {
        "domain": {"type": "string"},
        "focus_topic": {"type": "string"},
        "perspective": {"type": "string"},
        "primary_question": {"type": "string"},
        "companies": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "ticker": {"type": "string"},
                    "cik": {"type": "string"},
                    "role": {"type": "string"},
                    "aliases": {"type": "string"},
                },
            },
        },
        "grounding_queries": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "query": {"type": "string"},
                    "company": {"type": "string"},
                },
            },
        },
        "news_queries": {"type": "array", "items": {"type": "string"}},
        "sec_fulltext_queries": {"type": "array", "items": {"type": "string"}},
        "financial_retrieval_query": {"type": "string"},
        "qualitative_retrieval_query": {"type": "string"},
        "memory_seeds": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "source": {"type": "string"},
                    "relation": {"type": "string"},
                    "target": {"type": "string"},
                },
            },
        },
        "extraction_companies": {"type": "object"},
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# CIK lookup via SEC EDGAR (fallback when LLM doesn't know CIK)
# ═══════════════════════════════════════════════════════════════════════════
def _lookup_cik(ticker: str) -> str:
    """Attempt to resolve a stock ticker to a SEC CIK number.

    Uses the SEC EDGAR company tickers JSON endpoint.
    Returns zero-padded 10-digit CIK or empty string on failure.
    """
    try:
        import requests
        url = "https://www.sec.gov/files/company_tickers.json"
        r = requests.get(url, headers={
            "User-Agent": "StrategicAnalysisBot/1.0 (contact: analysis@example.com)"
        }, timeout=10)
        if r.status_code != 200:
            return ""
        data = r.json()
        ticker_upper = ticker.upper().strip()
        for entry in data.values():
            if entry.get("ticker", "").upper() == ticker_upper:
                return str(entry.get("cik_str", "")).zfill(10)
    except Exception as exc:
        logger.warning("CIK lookup failed for %s: %s", ticker, exc)
    return ""


# ═══════════════════════════════════════════════════════════════════════════
# Main entry point
# ═══════════════════════════════════════════════════════════════════════════
def generate_search_plan(prompt: str, llm: "GeminiClient") -> SearchPlan:
    """Use the LLM to generate a SearchPlan from the user's question.

    This is called once at the start of deep_analysis(), before any data
    fetching happens. The resulting SearchPlan drives all downstream steps.

    Args:
        prompt: The user's original question.
        llm: GeminiClient instance for the planning LLM call.

    Returns:
        A populated SearchPlan dataclass.
    """
    logger.info("Generating search plan for: %.120s", prompt)

    resp = llm.generate(
        prompt,
        system=_PLANNER_SYSTEM,
        json_mode=True,
        response_schema=_PLANNER_SCHEMA,
        thinking_budget=1024,
        temperature=0.1,
        max_tokens=4096,
    )

    try:
        data = _parse_plan(resp.text)
    except Exception as exc:
        logger.warning("Search plan parse failed (%s) — using fallback", exc)
        data = _fallback_plan(prompt)

    plan = _build_plan(data, prompt)

    # ── Validate and fix CIK numbers ─────────────────────────────
    for company in plan.companies:
        cik = company.get("cik", "")
        if not cik or len(cik) < 5:
            ticker = company.get("ticker", "")
            if ticker:
                logger.info("CIK missing for %s — attempting lookup", ticker)
                resolved = _lookup_cik(ticker)
                if resolved:
                    company["cik"] = resolved
                    logger.info("CIK resolved: %s → %s", ticker, resolved)

    logger.info(
        "Search plan ready: domain=%s companies=%s queries=%d news=%d sec=%d",
        plan.domain,
        [c.get("ticker", "?") for c in plan.companies],
        len(plan.grounding_queries),
        len(plan.news_queries),
        len(plan.sec_fulltext_queries),
    )
    return plan


def _parse_plan(text: str) -> dict:
    """Parse the LLM's JSON response into a dict."""
    from llm_client import GeminiClient
    cleaned = GeminiClient._clean_json_text(text)
    return GeminiClient.parse_json(cleaned)


def _build_plan(data: dict, original_prompt: str) -> SearchPlan:
    """Convert a parsed JSON dict into a SearchPlan dataclass."""
    return SearchPlan(
        domain=data.get("domain", "general"),
        focus_topic=data.get("focus_topic", ""),
        perspective=data.get("perspective", "an industry analyst"),
        primary_question=data.get("primary_question", original_prompt),
        original_prompt=original_prompt,
        companies=data.get("companies", []),
        grounding_queries=data.get("grounding_queries", []),
        news_queries=data.get("news_queries", []),
        sec_fulltext_queries=data.get("sec_fulltext_queries", []),
        financial_retrieval_query=data.get("financial_retrieval_query", ""),
        qualitative_retrieval_query=data.get("qualitative_retrieval_query", ""),
        memory_seeds=data.get("memory_seeds", []),
        extraction_companies=data.get("extraction_companies", {}),
    )


def _fallback_plan(prompt: str) -> dict:
    """Generate a basic plan when LLM parsing fails.

    Extracts company-like words from the prompt and builds minimal
    grounding queries around them.
    """
    logger.warning("Using fallback plan generation for: %.80s", prompt)
    # Try to extract capitalized multi-word names (crude heuristic)
    words = prompt.split()
    return {
        "domain": "general",
        "focus_topic": prompt[:100],
        "perspective": "an industry analyst",
        "primary_question": prompt,
        "companies": [],
        "grounding_queries": [
            {"query": prompt, "company": "cross_market"},
            {"query": f"latest news: {prompt[:100]}", "company": "cross_market"},
        ],
        "news_queries": ["+".join(words[:6])],
        "sec_fulltext_queries": [" ".join(words[:5])],
        "financial_retrieval_query": prompt[:150],
        "qualitative_retrieval_query": prompt[:150],
        "memory_seeds": [],
        "extraction_companies": {},
    }
